[project]
name = "applied-time-series-and-machine-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "groq>=0.26.0",
    "ipdb>=0.13.13",
    "openai>=1.83.0",
    "transformers>=4.52.4",
]
